// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as MenuButtonDemo$Reach from "./MenuButtonDemo.bs.js";

var className = Css.style(/* :: */[
      Css.marginRight(/* `px */[
            25096,
            10
          ]),
      /* [] */0
    ]);

function Demo$Index(Props) {
  return React.createElement(React.Fragment, undefined, $$Array.of_list(List.map((function (url) {
                        return React.createElement("div", {
                                    key: url,
                                    className: className
                                  }, React.createElement("a", {
                                        href: "/" + url
                                      }, url));
                      }), /* :: */[
                      "menu-button",
                      /* :: */[
                        "dialog",
                        /* :: */[
                          "tooltip",
                          /* [] */0
                        ]
                      ]
                    ])));
}

var Index = {
  className: className,
  make: Demo$Index
};

function Demo(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url.path;
  if (match && match[0] === "menu-button" && !match[1]) {
    return React.createElement(MenuButtonDemo$Reach.make, { });
  }
  return React.createElement(Demo$Index, { });
}

var make = Demo;

export {
  Index ,
  make ,
  
}
/* className Not a pure module */
