// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as FocusVisibleJsx from "./FocusVisible.jsx";

function useFocusVisible_(prim) {
  return FocusVisibleJsx.useFocusVisible(prim);
}

function useFocusVisible(i) {
  var rawProps = FocusVisibleJsx.useFocusVisible(i);
  return {
          onFocus: rawProps.onFocus,
          onBlur: rawProps.onBlur,
          "data-focus-visible": rawProps["data-focus-visible"],
          className: rawProps["data-focus-visible"] ? " data-focus-visible " : ""
        };
}

var focusStyle_000 = Css.focus(/* :: */[
      Css.outlineStyle(/* none */-922086728),
      /* [] */0
    ]);

var focusStyle_001 = /* :: */[
  Css.selector("&.data-focus-visible", /* :: */[
        Css.unsafe("filter", "drop-shadow(0px 0px 6px rgb(0,93,225))"),
        /* [] */0
      ]),
  /* [] */0
];

var focusStyle = /* :: */[
  focusStyle_000,
  focusStyle_001
];

export {
  useFocusVisible_ ,
  useFocusVisible ,
  focusStyle ,
  
}
/* focusStyle Not a pure module */
