// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Demo$Reach from "./Demo.bs.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";

ReactDOMRe.renderToElementWithId(React.createElement(Demo$Reach.make, { }), "app");

export {
  
}
/*  Not a pure module */
