// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as FocusVisible$Reach from "./FocusVisible.bs.js";
import * as Dist from "@reach/menu-button/dist";

var buttonStyle = Css.style(/* :: */[
      Css.unsafe("border", "none"),
      /* :: */[
        Css.unsafe("color", "inherit"),
        /* :: */[
          Css.unsafe("font", "inherit"),
          /* :: */[
            Css.unsafe("text-align", "inherit"),
            /* :: */[
              Css.unsafe("-webkit-font-smoothing", "inherit"),
              /* :: */[
                Css.unsafe("-webkit-appearance", "none"),
                /* :: */[
                  Css.lineHeight(/* normal */812216871),
                  /* :: */[
                    Css.background(/* transparent */582626130),
                    /* :: */[
                      Css.overflow(/* visible */589592690),
                      /* :: */[
                        Css.width(/* auto */-1065951377),
                        /* :: */[
                          Css.display(/* flex */-1010954439),
                          FocusVisible$Reach.focusStyle
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var listStyle = Css.style(/* :: */[
      Css.borderColor(Css.rgb(200, 200, 200)),
      /* :: */[
        Css.color(Css.rgb(0, 0, 0)),
        /* :: */[
          Css.minWidth(/* `rem */[
                5691738,
                12
              ]),
          /* [] */0
        ]
      ]
    ]);

function MenuButtonDemo(Props) {
  var match = FocusVisible$Reach.useFocusVisible(undefined);
  return React.createElement(Dist.Menu, {
              children: null
            }, React.createElement(Dist.MenuButton, {
                  className: buttonStyle + match.className,
                  onFocus: match.onFocus,
                  onBlur: match.onBlur,
                  children: React.createElement("img", {
                        className: Css.style(/* :: */[
                              Css.width(/* `px */[
                                    25096,
                                    50
                                  ]),
                              /* :: */[
                                Css.height(/* `px */[
                                      25096,
                                      50
                                    ]),
                                /* :: */[
                                  Css.borderRadius(/* `percent */[
                                        -119887163,
                                        50
                                      ]),
                                  /* [] */0
                                ]
                              ]
                            ]),
                        src: "https://randomuser.me/api/portraits/women/53.jpg"
                      })
                }), React.createElement(Dist.MenuList, {
                  className: listStyle,
                  children: null
                }, React.createElement(Dist.MenuItem, {
                      children: "Download",
                      onSelect: (function (param) {
                          console.log("Download");
                          return /* () */0;
                        })
                    }), React.createElement(Dist.MenuItem, {
                      children: "Create a Copy",
                      onSelect: (function (param) {
                          console.log("Copy");
                          return /* () */0;
                        })
                    }), React.createElement(Dist.MenuItem, {
                      children: "Mark as Draft",
                      onSelect: (function (param) {
                          console.log("Mark as Draft");
                          return /* () */0;
                        })
                    }), React.createElement(Dist.MenuItem, {
                      children: "Delete",
                      onSelect: (function (param) {
                          console.log("Delete");
                          return /* () */0;
                        })
                    }), React.createElement(Dist.MenuLink, {
                      children: "Attend a Workshop",
                      as_: "a",
                      href: "https://reacttraining.com/workshops/"
                    })));
}

var make = MenuButtonDemo;

export {
  buttonStyle ,
  listStyle ,
  make ,
  
}
/* buttonStyle Not a pure module */
