// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var TabList = { };

var Tab = { };

var TabPanels = { };

var TabPanel = { };

export {
  TabList ,
  Tab ,
  TabPanels ,
  TabPanel ,
  
}
/* No side effect */
